#!/bin/sh

if [ $# != 2 ]; then
    echo "Usage: $0 ICON-GRAPHIC ICONSET-NAME"
    exit 1
fi

mkdir $2
sips -z 16 16     $1 --out $2/icon_16x16.png
sips -z 32 32     $1 --out $2/icon_16x16@2x.png
sips -z 32 32     $1 --out $2/icon_32x32.png
sips -z 64 64     $1 --out $2/icon_32x32@2x.png
sips -z 128 128   $1 --out $2/icon_128x128.png
sips -z 256 256   $1 --out $2/icon_128x128@2x.png
sips -z 256 256   $1 --out $2/icon_256x256.png
sips -z 512 512   $1 --out $2/icon_256x256@2x.png
sips -z 512 512   $1 --out $2/icon_512x512.png
cp $1 $2/icon_512x512@2x.png
#sips -z 1024 1024 $1 --out $2/icon_512x512@2x.png
iconutil -c icns $2
rm -R $2
